spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

server:
  port: 8004

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
#logging:
#  level:
#    org.springframework.cloud.gateway: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
