spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: consumer
          uri: lb://CONSUMER
          predicates:
            - Path=/consumer/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/consumer/fallback

server:
  port: 8004

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
#logging:
#  level:
#    org.springframework.cloud.gateway: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
